modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="colacaomod"
version="0.1.0"
displayName="ColaCao Mod"
logoFile="colacaomod.png"
credits="WifftLord"
authors="Wifft"
description='''
Minecraft with ColaCao is better
'''
[[dependencies.colacaomod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colacaomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
